# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#######################################
## Healthcare Dataset and Datastores ##
#######################################

# This sections sets up billing acccount and folder under which the projects must be deployed
overall:
  billing_account: XXXXXX-XXXXXX-XXXXXX
  domain: dpt.healthcare
  # Optional ID of the organization that the projects will be created under (pattern: ^[0-9]{8,25}$)
  # organization_id:
  # Optional ID of the folder that the projects will be created under (pattern: ^[0-9]{8,25}$)
  # folder_id:

generated_fields_path: ./generated_fields.yaml

# projects deployed in the cloud are listed
projects:
  # projects' names and the thier groups must be changed as necessary
  - project_id: example-project
    owners_group: ownergroup@domain
    auditors_group: auditgroup@domain

    # Storage bucket stores the terraform states of the resources in the projects.
    devops:
      state_storage_bucket:
        name: data-state
        location: EU

    # Bigquery dataset stores audit logs of the project and it's resources
    # Storage bucket holds GCS logs if the project has storage buckets
    audit:
      logs_bigquery_dataset:
        dataset_id: data_logs
        location: EU
      logs_storage_bucket:
        name: data-logs
        location: EU

    # datastores for personal data which aid in features of Healthcare API
    healthcare_datasets:
      # appropriate name must be chosen based on its purpose
      - name: healthcare-datasets
        location: us-central1
        # IAM Role Binding
        # role-member bindings can be added/removed as required
        _iam_members:
          - role: roles/healthcare.datasetViewer
            member: user:user@domain
          - role: roles/healthcare.datasetViewer
            member: user:user@domain
        _dicom_stores:
          # appropriate name must be chosen based on its purpose
          - name: dicom-store
            # role-member bindings can be added/removed as required
            _iam_members:
              - role: roles/healthcare.dicomEditor
                member: user:user@domain
              - role: roles/healthcare.dicomStoreAdmin
                member: user:user@domain
        _fhir_stores:
          # appropriate name must be chosen based on its purpose
          - name: fhir-store
            # role-member bindings can be added/removed as required
            _iam_members:
              - role: roles/healthcare.fhirResourceReader
                member: user:user@domain
              - role: roles/healthcare.fhirResourceEditor
                member: user:user@domain
        _hl7_v2_stores:
          # appropriate name must be chosen based on its purpose
          - name: hl7-v2-store
            # role-member bindings can be added/removed as required
            _iam_members:
              - role: roles/healthcare.hl7V2StoreAdmin
                member: user:user@domain
              - role: roles/healthcare.hl7V2Ingest
                member: user:user@domain
              - role: roles/healthcare.hl7V2Editor
                member: user:user@domain
